run: Grafica.class

	java Grafica

Grafica.class:Grafica.java

	javac Grafica.java

Vertice.class:Vertice.java

	javac Vertice.java

Arista.class:Arista.java

	javac Arista.java

Lector.class:Lector.java

	javac Lector.java

clean:rm Grafica.class Vertice.class Arista.class Lector.class